proxies:
  -
    name: 香港｜私人定制
    type: ssr
    server: gqwnvbf7yxh.boyan.wiki
    port: 5420
    password: V2efLnR3SJZrd
    cipher: aes-256-cfb
    protocol: auth_aes128_sha1
    obfs: http_simple
    protocol-param: 2:sK0PUK
    obfs-param: ee49a2.microsoft.com
    udp: true
