#---------------------------------------------------#
## 上次更新于：2022-06-14 12:20:59
#---------------------------------------------------#

port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  -
    name: 香港｜私人定制
    type: ssr
    server: gqwnvbf7yxh.boyan.wiki
    port: 5420
    password: V2efLnR3SJZr
    cipher: aes-256-cfb
    protocol: auth_aes128_sha1
    obfs: http_simple
    protocol-param: 2:sK0PUK
    obfs-param: ee49a2.microsoft.com
    udp: true
